const CONFIG = {
    titleWeb: "công chúa hết giận nếu hog là chích 1 cái nhó",
    introTitle: 'Nguyễn thị trà my ',
    introDesc: `nếu thoát ra là đã đồng ý chích 1 cái gòi đó `,
    btnIntro: '^^HiHi^^',
    title: 'công chúa thôi giận anh nhó  🥰',
    desc: 'đừng giận tùng nữa nhó ',
    btnYes: 'dạaaa <33',
    btnNo: 'đéo :3',
    question: 'nói tùng bt tại sao lại hết giận đii <3',
    btnReply: 'Gửi cho công chúa <3',
    reply: 'bởi vì iuuuu thanh tùngggg <33333333',
    mess: 'anh biết mà 🥰. Yêu em nhiều nhiều 😘😘',
    messDesc: 'tối nay chúng taaa chích 1 cái nhó.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'https://www.facebook.com/messages/t/100078108201099
